[package]
name = "linkerd-metrics"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
license = "Apache-2.0"
edition = "2021"
publish = false

[features]
default = []
app = ["process", "tokio-rt", "stack"]
process = ["dep:kubert-prometheus-process"]
tokio-rt = ["dep:kubert-prometheus-tokio"]
stack = ["linkerd-stack"]
test_util = []

[dependencies]
deflate = { version = "1", features = ["gzip"] }
http = "0.2"
hyper = { version = "0.14", features = ["http1", "http2"] }
kubert-prometheus-process = { version = "0.1", optional = true }
linkerd-stack = { path = "../stack", optional = true }
parking_lot = "0.12"
prometheus-client = "0.22"
tokio = { version = "1", features = ["time"] }
tracing = "0.1"

[target.'cfg(tokio_unstable)'.dependencies.kubert-prometheus-tokio]
version = "0.1.0"
optional = true
features = ["rt"]

[dev-dependencies]
quickcheck = { version = "1", default-features = false }
tokio = { version = "1", features = ["rt", "macros", "test-util", "time"] }
